# Generated by Django 5.2 on 2025-07-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='pocemons_images/', verbose_name='изображение покемона'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='предыдущая эволюция покемона'),
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appear_at', models.DateTimeField(verbose_name='дата и время появления')),
                ('disappear_at', models.DateTimeField(blank=True, null=True, verbose_name='дата и время исчезновения')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('health', models.PositiveIntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.PositiveIntegerField(blank=True, null=True, verbose_name='Атака')),
                ('defence', models.PositiveIntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='покемон')),
            ],
        ),
    ]
