# Generated by Django 5.2 on 2025-07-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_rename_title_pokemon_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon', to='pokemon_entities.pokemon', verbose_name='покемон'),
        ),
    ]
